//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Gorvodokanal
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Address.
    /// </summary>
    // *** Start programmer edit section *** (Address CustomAttributes)

    // *** End programmer edit section *** (Address CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("AddressE", new string[] {
            "Index as \'Код адреса\'",
            "Street as \'Улица\'",
            "House as \'Дом\'",
            "Build as \'Корпус\'",
            "Floor as \'Этаж\'",
            "Apartment as \'Квартира\'"})]
    [View("AddressL", new string[] {
            "Index as \'Код адреса\'",
            "Street as \'Улица\'",
            "House as \'Дом\'",
            "Build as \'Корпус\'",
            "Floor as \'Этаж\'",
            "Apartment as \'Квартира\'"})]
    public class Address : ICSSoft.STORMNET.DataObject
    {
        
        private int fIndex = 1;
        
        private string fStreet;
        
        private int fHouse;
        
        private string fBuild;
        
        private ICSSoft.STORMNET.UserDataTypes.NullableInt fFloor;
        
        private ICSSoft.STORMNET.UserDataTypes.NullableInt fApartment;
        
        // *** Start programmer edit section *** (Address CustomMembers)

        // *** End programmer edit section *** (Address CustomMembers)

        
        /// <summary>
        /// Index.
        /// </summary>
        // *** Start programmer edit section *** (Address.Index CustomAttributes)

        // *** End programmer edit section *** (Address.Index CustomAttributes)
        [DisableInsertProperty(true)]
        [NotNull()]
        public virtual int Index
        {
            get
            {
                // *** Start programmer edit section *** (Address.Index Get start)

                // *** End programmer edit section *** (Address.Index Get start)
                int result = this.fIndex;
                // *** Start programmer edit section *** (Address.Index Get end)

                // *** End programmer edit section *** (Address.Index Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Address.Index Set start)

                // *** End programmer edit section *** (Address.Index Set start)
                this.fIndex = value;
                // *** Start programmer edit section *** (Address.Index Set end)

                // *** End programmer edit section *** (Address.Index Set end)
            }
        }
        
        /// <summary>
        /// Street.
        /// </summary>
        // *** Start programmer edit section *** (Address.Street CustomAttributes)

        // *** End programmer edit section *** (Address.Street CustomAttributes)
        [StrLen(255)]
        [NotNull()]
        public virtual string Street
        {
            get
            {
                // *** Start programmer edit section *** (Address.Street Get start)

                // *** End programmer edit section *** (Address.Street Get start)
                string result = this.fStreet;
                // *** Start programmer edit section *** (Address.Street Get end)

                // *** End programmer edit section *** (Address.Street Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Address.Street Set start)

                // *** End programmer edit section *** (Address.Street Set start)
                this.fStreet = value;
                // *** Start programmer edit section *** (Address.Street Set end)

                // *** End programmer edit section *** (Address.Street Set end)
            }
        }
        
        /// <summary>
        /// House.
        /// </summary>
        // *** Start programmer edit section *** (Address.House CustomAttributes)

        // *** End programmer edit section *** (Address.House CustomAttributes)
        [NotNull()]
        public virtual int House
        {
            get
            {
                // *** Start programmer edit section *** (Address.House Get start)

                // *** End programmer edit section *** (Address.House Get start)
                int result = this.fHouse;
                // *** Start programmer edit section *** (Address.House Get end)

                // *** End programmer edit section *** (Address.House Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Address.House Set start)

                // *** End programmer edit section *** (Address.House Set start)
                this.fHouse = value;
                // *** Start programmer edit section *** (Address.House Set end)

                // *** End programmer edit section *** (Address.House Set end)
            }
        }
        
        /// <summary>
        /// Build.
        /// </summary>
        // *** Start programmer edit section *** (Address.Build CustomAttributes)

        // *** End programmer edit section *** (Address.Build CustomAttributes)
        [StrLen(255)]
        public virtual string Build
        {
            get
            {
                // *** Start programmer edit section *** (Address.Build Get start)

                // *** End programmer edit section *** (Address.Build Get start)
                string result = this.fBuild;
                // *** Start programmer edit section *** (Address.Build Get end)

                // *** End programmer edit section *** (Address.Build Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Address.Build Set start)

                // *** End programmer edit section *** (Address.Build Set start)
                this.fBuild = value;
                // *** Start programmer edit section *** (Address.Build Set end)

                // *** End programmer edit section *** (Address.Build Set end)
            }
        }
        
        /// <summary>
        /// Floor.
        /// </summary>
        // *** Start programmer edit section *** (Address.Floor CustomAttributes)

        // *** End programmer edit section *** (Address.Floor CustomAttributes)
        public virtual ICSSoft.STORMNET.UserDataTypes.NullableInt Floor
        {
            get
            {
                // *** Start programmer edit section *** (Address.Floor Get start)

                // *** End programmer edit section *** (Address.Floor Get start)
                ICSSoft.STORMNET.UserDataTypes.NullableInt result = this.fFloor;
                // *** Start programmer edit section *** (Address.Floor Get end)

                // *** End programmer edit section *** (Address.Floor Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Address.Floor Set start)

                // *** End programmer edit section *** (Address.Floor Set start)
                this.fFloor = value;
                // *** Start programmer edit section *** (Address.Floor Set end)

                // *** End programmer edit section *** (Address.Floor Set end)
            }
        }
        
        /// <summary>
        /// Apartment.
        /// </summary>
        // *** Start programmer edit section *** (Address.Apartment CustomAttributes)

        // *** End programmer edit section *** (Address.Apartment CustomAttributes)
        public virtual ICSSoft.STORMNET.UserDataTypes.NullableInt Apartment
        {
            get
            {
                // *** Start programmer edit section *** (Address.Apartment Get start)

                // *** End programmer edit section *** (Address.Apartment Get start)
                ICSSoft.STORMNET.UserDataTypes.NullableInt result = this.fApartment;
                // *** Start programmer edit section *** (Address.Apartment Get end)

                // *** End programmer edit section *** (Address.Apartment Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Address.Apartment Set start)

                // *** End programmer edit section *** (Address.Apartment Set start)
                this.fApartment = value;
                // *** Start programmer edit section *** (Address.Apartment Set end)

                // *** End programmer edit section *** (Address.Apartment Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "AddressE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View AddressE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("AddressE", typeof(IIS.Gorvodokanal.Address));
                }
            }
            
            /// <summary>
            /// "AddressL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View AddressL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("AddressL", typeof(IIS.Gorvodokanal.Address));
                }
            }
        }
    }
}
