//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Gorvodokanal
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Address.
    /// </summary>
    // *** Start programmer edit section *** (Address CustomAttributes)

    // *** End programmer edit section *** (Address CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("AddressE", new string[] {
            "index as \'Индекс адреса\'",
            "street as \'Улица\'",
            "house as \'Дом\'",
            "build as \'Корпус\'",
            "floor as \'Этаж\'",
            "flat as \'Квартира\'"})]
    [View("AddressL", new string[] {
            "index as \'Индекс адреса\'",
            "street as \'Улица\'",
            "house as \'Дом\'",
            "build as \'Корпус\'",
            "floor as \'Этаж\'",
            "flat as \'Квартира\'"}, Hidden=new string[] {
            "index"})]
    public class Address : ICSSoft.STORMNET.DataObject
    {
        
        private int findex;
        
        private string fstreet;
        
        private int fhouse;
        
        private string fbuild;
        
        private ICSSoft.STORMNET.UserDataTypes.NullableInt ffloor;
        
        private ICSSoft.STORMNET.UserDataTypes.NullableInt fflat;
        
        // *** Start programmer edit section *** (Address CustomMembers)

        // *** End programmer edit section *** (Address CustomMembers)

        
        /// <summary>
        /// index.
        /// </summary>
        // *** Start programmer edit section *** (Address.index CustomAttributes)

        // *** End programmer edit section *** (Address.index CustomAttributes)
        [NotNull()]
        public virtual int index
        {
            get
            {
                // *** Start programmer edit section *** (Address.index Get start)

                // *** End programmer edit section *** (Address.index Get start)
                int result = this.findex;
                // *** Start programmer edit section *** (Address.index Get end)

                // *** End programmer edit section *** (Address.index Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Address.index Set start)

                // *** End programmer edit section *** (Address.index Set start)
                this.findex = value;
                // *** Start programmer edit section *** (Address.index Set end)

                // *** End programmer edit section *** (Address.index Set end)
            }
        }
        
        /// <summary>
        /// street.
        /// </summary>
        // *** Start programmer edit section *** (Address.street CustomAttributes)

        // *** End programmer edit section *** (Address.street CustomAttributes)
        [StrLen(255)]
        [NotNull()]
        public virtual string street
        {
            get
            {
                // *** Start programmer edit section *** (Address.street Get start)

                // *** End programmer edit section *** (Address.street Get start)
                string result = this.fstreet;
                // *** Start programmer edit section *** (Address.street Get end)

                // *** End programmer edit section *** (Address.street Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Address.street Set start)

                // *** End programmer edit section *** (Address.street Set start)
                this.fstreet = value;
                // *** Start programmer edit section *** (Address.street Set end)

                // *** End programmer edit section *** (Address.street Set end)
            }
        }
        
        /// <summary>
        /// house.
        /// </summary>
        // *** Start programmer edit section *** (Address.house CustomAttributes)

        // *** End programmer edit section *** (Address.house CustomAttributes)
        [NotNull()]
        public virtual int house
        {
            get
            {
                // *** Start programmer edit section *** (Address.house Get start)

                // *** End programmer edit section *** (Address.house Get start)
                int result = this.fhouse;
                // *** Start programmer edit section *** (Address.house Get end)

                // *** End programmer edit section *** (Address.house Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Address.house Set start)

                // *** End programmer edit section *** (Address.house Set start)
                this.fhouse = value;
                // *** Start programmer edit section *** (Address.house Set end)

                // *** End programmer edit section *** (Address.house Set end)
            }
        }
        
        /// <summary>
        /// build.
        /// </summary>
        // *** Start programmer edit section *** (Address.build CustomAttributes)

        // *** End programmer edit section *** (Address.build CustomAttributes)
        [StrLen(255)]
        public virtual string build
        {
            get
            {
                // *** Start programmer edit section *** (Address.build Get start)

                // *** End programmer edit section *** (Address.build Get start)
                string result = this.fbuild;
                // *** Start programmer edit section *** (Address.build Get end)

                // *** End programmer edit section *** (Address.build Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Address.build Set start)

                // *** End programmer edit section *** (Address.build Set start)
                this.fbuild = value;
                // *** Start programmer edit section *** (Address.build Set end)

                // *** End programmer edit section *** (Address.build Set end)
            }
        }
        
        /// <summary>
        /// floor.
        /// </summary>
        // *** Start programmer edit section *** (Address.floor CustomAttributes)

        // *** End programmer edit section *** (Address.floor CustomAttributes)
        public virtual ICSSoft.STORMNET.UserDataTypes.NullableInt floor
        {
            get
            {
                // *** Start programmer edit section *** (Address.floor Get start)

                // *** End programmer edit section *** (Address.floor Get start)
                ICSSoft.STORMNET.UserDataTypes.NullableInt result = this.ffloor;
                // *** Start programmer edit section *** (Address.floor Get end)

                // *** End programmer edit section *** (Address.floor Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Address.floor Set start)

                // *** End programmer edit section *** (Address.floor Set start)
                this.ffloor = value;
                // *** Start programmer edit section *** (Address.floor Set end)

                // *** End programmer edit section *** (Address.floor Set end)
            }
        }
        
        /// <summary>
        /// flat.
        /// </summary>
        // *** Start programmer edit section *** (Address.flat CustomAttributes)

        // *** End programmer edit section *** (Address.flat CustomAttributes)
        public virtual ICSSoft.STORMNET.UserDataTypes.NullableInt flat
        {
            get
            {
                // *** Start programmer edit section *** (Address.flat Get start)

                // *** End programmer edit section *** (Address.flat Get start)
                ICSSoft.STORMNET.UserDataTypes.NullableInt result = this.fflat;
                // *** Start programmer edit section *** (Address.flat Get end)

                // *** End programmer edit section *** (Address.flat Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Address.flat Set start)

                // *** End programmer edit section *** (Address.flat Set start)
                this.fflat = value;
                // *** Start programmer edit section *** (Address.flat Set end)

                // *** End programmer edit section *** (Address.flat Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "AddressE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View AddressE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("AddressE", typeof(IIS.Gorvodokanal.Address));
                }
            }
            
            /// <summary>
            /// "AddressL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View AddressL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("AddressL", typeof(IIS.Gorvodokanal.Address));
                }
            }
        }
    }
}
