//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Gorvodokanal
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Category list.
    /// </summary>
    // *** Start programmer edit section *** (CategoryList CustomAttributes)

    // *** End programmer edit section *** (CategoryList CustomAttributes)
    [AutoAltered()]
    [Caption("Category list")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("CategoryListE", new string[] {
            "Category as \'Категория\'"})]
    [MasterViewDefineAttribute("CategoryListE", "Category", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Name")]
    public class CategoryList : ICSSoft.STORMNET.DataObject
    {
        
        private IIS.Gorvodokanal.Category fCategory;
        
        private IIS.Gorvodokanal.Team fTeam;
        
        // *** Start programmer edit section *** (CategoryList CustomMembers)

        // *** End programmer edit section *** (CategoryList CustomMembers)

        
        /// <summary>
        /// Category list.
        /// </summary>
        // *** Start programmer edit section *** (CategoryList.Category CustomAttributes)

        // *** End programmer edit section *** (CategoryList.Category CustomAttributes)
        [PropertyStorage(new string[] {
                "Category"})]
        [NotNull()]
        public virtual IIS.Gorvodokanal.Category Category
        {
            get
            {
                // *** Start programmer edit section *** (CategoryList.Category Get start)

                // *** End programmer edit section *** (CategoryList.Category Get start)
                IIS.Gorvodokanal.Category result = this.fCategory;
                // *** Start programmer edit section *** (CategoryList.Category Get end)

                // *** End programmer edit section *** (CategoryList.Category Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (CategoryList.Category Set start)

                // *** End programmer edit section *** (CategoryList.Category Set start)
                this.fCategory = value;
                // *** Start programmer edit section *** (CategoryList.Category Set end)

                // *** End programmer edit section *** (CategoryList.Category Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Gorvodokanal.Team.
        /// </summary>
        // *** Start programmer edit section *** (CategoryList.Team CustomAttributes)

        // *** End programmer edit section *** (CategoryList.Team CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Team"})]
        public virtual IIS.Gorvodokanal.Team Team
        {
            get
            {
                // *** Start programmer edit section *** (CategoryList.Team Get start)

                // *** End programmer edit section *** (CategoryList.Team Get start)
                IIS.Gorvodokanal.Team result = this.fTeam;
                // *** Start programmer edit section *** (CategoryList.Team Get end)

                // *** End programmer edit section *** (CategoryList.Team Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (CategoryList.Team Set start)

                // *** End programmer edit section *** (CategoryList.Team Set start)
                this.fTeam = value;
                // *** Start programmer edit section *** (CategoryList.Team Set end)

                // *** End programmer edit section *** (CategoryList.Team Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "CategoryListE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View CategoryListE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("CategoryListE", typeof(IIS.Gorvodokanal.CategoryList));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of CategoryList.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfCategoryList CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfCategoryList CustomAttributes)
    public class DetailArrayOfCategoryList : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Gorvodokanal.DetailArrayOfCategoryList members)

        // *** End programmer edit section *** (IIS.Gorvodokanal.DetailArrayOfCategoryList members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type CategoryList by index.
        /// </summary>
        /// <summary>
        /// Adds object with type CategoryList.
        /// </summary>
        public DetailArrayOfCategoryList(IIS.Gorvodokanal.Team fTeam) : 
                base(typeof(CategoryList), ((ICSSoft.STORMNET.DataObject)(fTeam)))
        {
        }
        
        public IIS.Gorvodokanal.CategoryList this[int index]
        {
            get
            {
                return ((IIS.Gorvodokanal.CategoryList)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Gorvodokanal.CategoryList dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
