//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Gorvodokanal
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Category.
    /// </summary>
    // *** Start programmer edit section *** (Category CustomAttributes)

    // *** End programmer edit section *** (Category CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("CategoryE", new string[] {
            "Code as \'Код\'",
            "Name as \'Наименование\'"}, Hidden=new string[] {
            "Code"})]
    [View("CategoryL", new string[] {
            "Code as \'Код\'",
            "Name as \'Наименование\'"})]
    public class Category : ICSSoft.STORMNET.DataObject
    {
        
        private int fCode = 1;
        
        private string fName;
        
        // *** Start programmer edit section *** (Category CustomMembers)

        // *** End programmer edit section *** (Category CustomMembers)

        
        /// <summary>
        /// Code.
        /// </summary>
        // *** Start programmer edit section *** (Category.Code CustomAttributes)

        // *** End programmer edit section *** (Category.Code CustomAttributes)
        [DisableInsertProperty(true)]
        [NotNull()]
        public virtual int Code
        {
            get
            {
                // *** Start programmer edit section *** (Category.Code Get start)

                // *** End programmer edit section *** (Category.Code Get start)
                int result = this.fCode;
                // *** Start programmer edit section *** (Category.Code Get end)

                // *** End programmer edit section *** (Category.Code Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Category.Code Set start)

                // *** End programmer edit section *** (Category.Code Set start)
                this.fCode = value;
                // *** Start programmer edit section *** (Category.Code Set end)

                // *** End programmer edit section *** (Category.Code Set end)
            }
        }
        
        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (Category.Name CustomAttributes)

        // *** End programmer edit section *** (Category.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (Category.Name Get start)

                // *** End programmer edit section *** (Category.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (Category.Name Get end)

                // *** End programmer edit section *** (Category.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Category.Name Set start)

                // *** End programmer edit section *** (Category.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (Category.Name Set end)

                // *** End programmer edit section *** (Category.Name Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "CategoryE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View CategoryE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("CategoryE", typeof(IIS.Gorvodokanal.Category));
                }
            }
            
            /// <summary>
            /// "CategoryL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View CategoryL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("CategoryL", typeof(IIS.Gorvodokanal.Category));
                }
            }
        }
    }
}
