//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Gorvodokanal
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Request.
    /// </summary>
    // *** Start programmer edit section *** (Request CustomAttributes)

    // *** End programmer edit section *** (Request CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("RequestE", new string[] {
            "Index",
            "PlaneDateStart",
            "Address as \'Адрес\' on \'-Данные об адресе\'",
            "IsAppointed as \'Отметка о назначении\' on \'-Данные о выполнении\'",
            "Team as \'Бригада\' on \'-Данные о выполнении\'",
            "DateStart as \'Дата выполнения работ\' on \'-Данные о выполнении\'",
            "IsCompleted as \'Отметка о выполнении\' on \'-Данные о выполнении\'",
            "DateEnd as \'Фактическое время окончания работ\' on \'-Данные о выполнении\'"}, Hidden=new string[] {
            "Index",
            "PlaneDateStart"})]
    [AssociatedDetailViewAttribute("RequestE", "Tasks", "TaskListE", true, "-Задачи", "", true, new string[] {
            ""})]
    [View("RequestL", new string[] {
            "Address.District as \'Адрес\' on \'-Данные об адресе\'",
            "Address.Street",
            "Address.House",
            "Address.Build",
            "Address.Porch",
            "Address.Floor",
            "Address.Apartment",
            "IsAppointed as \'Отметка о назначении\' on \'-Данные о выполнении\'",
            "Team.Index as \'Выполняющая бригада\' on \'-Данные о выполнении\'",
            "DateStart as \'Дата выполнения работ\' on \'-Данные о выполнении\'",
            "IsCompleted as \'Отметка о выполнении\' on \'-Данные о выполнении\'",
            "DateEnd as \'Фактическое время окончания работ\' on \'-Данные о выполнении\'",
            "Index",
            "PlaneDateStart"}, Hidden=new string[] {
            "Address.Street",
            "Address.House",
            "Address.Build",
            "Address.Porch",
            "Address.Floor",
            "Address.Apartment",
            "Index",
            "PlaneDateStart"})]
    [AssociatedDetailViewAttribute("RequestL", "Tasks", "TaskListE", true, "", "", false, new string[] {
            ""})]
    public class Request : ICSSoft.STORMNET.DataObject
    {
        
        private int fIndex = 1;
        
        private IIS.Gorvodokanal.tAppointed fIsAppointed;
        
        private ICSSoft.STORMNET.UserDataTypes.NullableDateTime fDateStart;
        
        private bool fIsCompleted = false;
        
        private ICSSoft.STORMNET.UserDataTypes.NullableDateTime fDateEnd;
        
        private ICSSoft.STORMNET.UserDataTypes.NullableDateTime fPlaneDateStart;
        
        private IIS.Gorvodokanal.Address fAddress;
        
        private IIS.Gorvodokanal.Team fTeam;
        
        private IIS.Gorvodokanal.DetailArrayOfTaskList fTasks;
        
        // *** Start programmer edit section *** (Request CustomMembers)

        // *** End programmer edit section *** (Request CustomMembers)

        
        /// <summary>
        /// Index.
        /// </summary>
        // *** Start programmer edit section *** (Request.Index CustomAttributes)

        // *** End programmer edit section *** (Request.Index CustomAttributes)
        [DisableInsertProperty(true)]
        [NotNull()]
        public virtual int Index
        {
            get
            {
                // *** Start programmer edit section *** (Request.Index Get start)

                // *** End programmer edit section *** (Request.Index Get start)
                int result = this.fIndex;
                // *** Start programmer edit section *** (Request.Index Get end)

                // *** End programmer edit section *** (Request.Index Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Request.Index Set start)

                // *** End programmer edit section *** (Request.Index Set start)
                this.fIndex = value;
                // *** Start programmer edit section *** (Request.Index Set end)

                // *** End programmer edit section *** (Request.Index Set end)
            }
        }
        
        /// <summary>
        /// IsAppointed.
        /// </summary>
        // *** Start programmer edit section *** (Request.IsAppointed CustomAttributes)

        // *** End programmer edit section *** (Request.IsAppointed CustomAttributes)
        [NotNull()]
        public virtual IIS.Gorvodokanal.tAppointed IsAppointed
        {
            get
            {
                // *** Start programmer edit section *** (Request.IsAppointed Get start)

                // *** End programmer edit section *** (Request.IsAppointed Get start)
                IIS.Gorvodokanal.tAppointed result = this.fIsAppointed;
                // *** Start programmer edit section *** (Request.IsAppointed Get end)

                // *** End programmer edit section *** (Request.IsAppointed Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Request.IsAppointed Set start)

                // *** End programmer edit section *** (Request.IsAppointed Set start)
                this.fIsAppointed = value;
                // *** Start programmer edit section *** (Request.IsAppointed Set end)

                // *** End programmer edit section *** (Request.IsAppointed Set end)
            }
        }
        
        /// <summary>
        /// DateStart.
        /// </summary>
        // *** Start programmer edit section *** (Request.DateStart CustomAttributes)

        // *** End programmer edit section *** (Request.DateStart CustomAttributes)
        public virtual ICSSoft.STORMNET.UserDataTypes.NullableDateTime DateStart
        {
            get
            {
                // *** Start programmer edit section *** (Request.DateStart Get start)

                // *** End programmer edit section *** (Request.DateStart Get start)
                ICSSoft.STORMNET.UserDataTypes.NullableDateTime result = this.fDateStart;
                // *** Start programmer edit section *** (Request.DateStart Get end)

                // *** End programmer edit section *** (Request.DateStart Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Request.DateStart Set start)

                // *** End programmer edit section *** (Request.DateStart Set start)
                this.fDateStart = value;
                // *** Start programmer edit section *** (Request.DateStart Set end)

                // *** End programmer edit section *** (Request.DateStart Set end)
            }
        }
        
        /// <summary>
        /// IsCompleted.
        /// </summary>
        // *** Start programmer edit section *** (Request.IsCompleted CustomAttributes)

        // *** End programmer edit section *** (Request.IsCompleted CustomAttributes)
        public virtual bool IsCompleted
        {
            get
            {
                // *** Start programmer edit section *** (Request.IsCompleted Get start)

                // *** End programmer edit section *** (Request.IsCompleted Get start)
                bool result = this.fIsCompleted;
                // *** Start programmer edit section *** (Request.IsCompleted Get end)

                // *** End programmer edit section *** (Request.IsCompleted Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Request.IsCompleted Set start)

                // *** End programmer edit section *** (Request.IsCompleted Set start)
                this.fIsCompleted = value;
                // *** Start programmer edit section *** (Request.IsCompleted Set end)

                // *** End programmer edit section *** (Request.IsCompleted Set end)
            }
        }
        
        /// <summary>
        /// DateEnd.
        /// </summary>
        // *** Start programmer edit section *** (Request.DateEnd CustomAttributes)

        // *** End programmer edit section *** (Request.DateEnd CustomAttributes)
        public virtual ICSSoft.STORMNET.UserDataTypes.NullableDateTime DateEnd
        {
            get
            {
                // *** Start programmer edit section *** (Request.DateEnd Get start)

                // *** End programmer edit section *** (Request.DateEnd Get start)
                ICSSoft.STORMNET.UserDataTypes.NullableDateTime result = this.fDateEnd;
                // *** Start programmer edit section *** (Request.DateEnd Get end)

                // *** End programmer edit section *** (Request.DateEnd Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Request.DateEnd Set start)

                // *** End programmer edit section *** (Request.DateEnd Set start)
                this.fDateEnd = value;
                // *** Start programmer edit section *** (Request.DateEnd Set end)

                // *** End programmer edit section *** (Request.DateEnd Set end)
            }
        }
        
        /// <summary>
        /// PlaneDateStart.
        /// </summary>
        // *** Start programmer edit section *** (Request.PlaneDateStart CustomAttributes)

        // *** End programmer edit section *** (Request.PlaneDateStart CustomAttributes)
        public virtual ICSSoft.STORMNET.UserDataTypes.NullableDateTime PlaneDateStart
        {
            get
            {
                // *** Start programmer edit section *** (Request.PlaneDateStart Get start)

                // *** End programmer edit section *** (Request.PlaneDateStart Get start)
                ICSSoft.STORMNET.UserDataTypes.NullableDateTime result = this.fPlaneDateStart;
                // *** Start programmer edit section *** (Request.PlaneDateStart Get end)

                // *** End programmer edit section *** (Request.PlaneDateStart Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Request.PlaneDateStart Set start)

                // *** End programmer edit section *** (Request.PlaneDateStart Set start)
                this.fPlaneDateStart = value;
                // *** Start programmer edit section *** (Request.PlaneDateStart Set end)

                // *** End programmer edit section *** (Request.PlaneDateStart Set end)
            }
        }
        
        /// <summary>
        /// Request.
        /// </summary>
        // *** Start programmer edit section *** (Request.Address CustomAttributes)

        // *** End programmer edit section *** (Request.Address CustomAttributes)
        [PropertyStorage(new string[] {
                "Address"})]
        [NotNull()]
        public virtual IIS.Gorvodokanal.Address Address
        {
            get
            {
                // *** Start programmer edit section *** (Request.Address Get start)

                // *** End programmer edit section *** (Request.Address Get start)
                IIS.Gorvodokanal.Address result = this.fAddress;
                // *** Start programmer edit section *** (Request.Address Get end)

                // *** End programmer edit section *** (Request.Address Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Request.Address Set start)

                // *** End programmer edit section *** (Request.Address Set start)
                this.fAddress = value;
                // *** Start programmer edit section *** (Request.Address Set end)

                // *** End programmer edit section *** (Request.Address Set end)
            }
        }
        
        /// <summary>
        /// Request.
        /// </summary>
        // *** Start programmer edit section *** (Request.Team CustomAttributes)

        // *** End programmer edit section *** (Request.Team CustomAttributes)
        [PropertyStorage(new string[] {
                "Team"})]
        public virtual IIS.Gorvodokanal.Team Team
        {
            get
            {
                // *** Start programmer edit section *** (Request.Team Get start)

                // *** End programmer edit section *** (Request.Team Get start)
                IIS.Gorvodokanal.Team result = this.fTeam;
                // *** Start programmer edit section *** (Request.Team Get end)

                // *** End programmer edit section *** (Request.Team Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Request.Team Set start)

                // *** End programmer edit section *** (Request.Team Set start)
                this.fTeam = value;
                // *** Start programmer edit section *** (Request.Team Set end)

                // *** End programmer edit section *** (Request.Team Set end)
            }
        }
        
        /// <summary>
        /// Request.
        /// </summary>
        // *** Start programmer edit section *** (Request.Tasks CustomAttributes)

        // *** End programmer edit section *** (Request.Tasks CustomAttributes)
        public virtual IIS.Gorvodokanal.DetailArrayOfTaskList Tasks
        {
            get
            {
                // *** Start programmer edit section *** (Request.Tasks Get start)

                // *** End programmer edit section *** (Request.Tasks Get start)
                if ((this.fTasks == null))
                {
                    this.fTasks = new IIS.Gorvodokanal.DetailArrayOfTaskList(this);
                }
                IIS.Gorvodokanal.DetailArrayOfTaskList result = this.fTasks;
                // *** Start programmer edit section *** (Request.Tasks Get end)

                // *** End programmer edit section *** (Request.Tasks Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Request.Tasks Set start)

                // *** End programmer edit section *** (Request.Tasks Set start)
                this.fTasks = value;
                // *** Start programmer edit section *** (Request.Tasks Set end)

                // *** End programmer edit section *** (Request.Tasks Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "RequestE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View RequestE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("RequestE", typeof(IIS.Gorvodokanal.Request));
                }
            }
            
            /// <summary>
            /// "RequestL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View RequestL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("RequestL", typeof(IIS.Gorvodokanal.Request));
                }
            }
        }
    }
}
