//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Gorvodokanal
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Request.
    /// </summary>
    // *** Start programmer edit section *** (Request CustomAttributes)

    // *** End programmer edit section *** (Request CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("RequestE", new string[] {
            "index as \'Номер заявки\'",
            "Address as \'Адрес\' on \'-Данные об адресе\'",
            "Address.street as \'Улица\' on \'-Данные об адресе\'",
            "Address.house as \'Дом\' on \'-Данные об адресе\'",
            "Address.build as \'Корпус\' on \'-Данные об адресе\'",
            "Address.floor as \'Этаж\' on \'-Данные об адресе\'",
            "Address.flat as \'Квартира\' on \'-Данные об адресе\'",
            "isCompleted as \'Отметка о закреплении\' on \'-Данные о выполнении\'",
            "Team as \'Бригада\' on \'-Данные о выполнении\'",
            "Team.index as \'Номер бригады\' on \'-Данные о выполнении\'",
            "isAppointed as \'Отметка о выполнении\' on \'-Данные о выполнении\'",
            "realDuration as \'Фактическая длительность работ\' on \'-Данные о выполнении\'"})]
    [AssociatedDetailViewAttribute("RequestE", "Tasks", "TaskE", true, "", "Задачи", true, new string[] {
            ""})]
    [View("RequestL", new string[] {
            "index as \'Номер заявки\'",
            "Address.street as \'Улица\' on \'-Данные об адресе\'",
            "Address.house as \'Дом\' on \'-Данные об адресе\'",
            "Address.build as \'Корпус\' on \'-Данные об адресе\'",
            "Address.floor as \'Этаж\' on \'-Данные об адресе\'",
            "Address.flat as \'Квартира\' on \'-Данные об адресе\'",
            "isAppointed as \'Отметка о прикреплении\' on \'-Данные о выполнении\'",
            "Team.index as \'Номер выполняющей бригады\' on \'-Данные о выполнении\'",
            "isCompleted as \'Отметка о выполнении\' on \'-Данные о выполнении\'",
            "realDuration as \'Фактическая длительность работ\' on \'-Данные о выполнении\'"})]
    [AssociatedDetailViewAttribute("RequestL", "Tasks", "TaskE", true, "", "Задачи", true, new string[] {
            ""})]
    public class Request : ICSSoft.STORMNET.DataObject
    {
        
        private int findex;
        
        private IIS.Gorvodokanal.tAppointed fisAppointed;
        
        private System.DateTime fdate;
        
        private bool fisCompleted;
        
        private System.DateTime frealDuration;
        
        private IIS.Gorvodokanal.Team fTeam;
        
        private IIS.Gorvodokanal.Address fAddress;
        
        private IIS.Gorvodokanal.DetailArrayOfTask fTasks;
        
        // *** Start programmer edit section *** (Request CustomMembers)

        // *** End programmer edit section *** (Request CustomMembers)

        
        /// <summary>
        /// index.
        /// </summary>
        // *** Start programmer edit section *** (Request.index CustomAttributes)

        // *** End programmer edit section *** (Request.index CustomAttributes)
        [NotNull()]
        public virtual int index
        {
            get
            {
                // *** Start programmer edit section *** (Request.index Get start)

                // *** End programmer edit section *** (Request.index Get start)
                int result = this.findex;
                // *** Start programmer edit section *** (Request.index Get end)

                // *** End programmer edit section *** (Request.index Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Request.index Set start)

                // *** End programmer edit section *** (Request.index Set start)
                this.findex = value;
                // *** Start programmer edit section *** (Request.index Set end)

                // *** End programmer edit section *** (Request.index Set end)
            }
        }
        
        /// <summary>
        /// isAppointed.
        /// </summary>
        // *** Start programmer edit section *** (Request.isAppointed CustomAttributes)

        // *** End programmer edit section *** (Request.isAppointed CustomAttributes)
        [NotNull()]
        public virtual IIS.Gorvodokanal.tAppointed isAppointed
        {
            get
            {
                // *** Start programmer edit section *** (Request.isAppointed Get start)

                // *** End programmer edit section *** (Request.isAppointed Get start)
                IIS.Gorvodokanal.tAppointed result = this.fisAppointed;
                // *** Start programmer edit section *** (Request.isAppointed Get end)

                // *** End programmer edit section *** (Request.isAppointed Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Request.isAppointed Set start)

                // *** End programmer edit section *** (Request.isAppointed Set start)
                this.fisAppointed = value;
                // *** Start programmer edit section *** (Request.isAppointed Set end)

                // *** End programmer edit section *** (Request.isAppointed Set end)
            }
        }
        
        /// <summary>
        /// date.
        /// </summary>
        // *** Start programmer edit section *** (Request.date CustomAttributes)

        // *** End programmer edit section *** (Request.date CustomAttributes)
        public virtual System.DateTime date
        {
            get
            {
                // *** Start programmer edit section *** (Request.date Get start)

                // *** End programmer edit section *** (Request.date Get start)
                System.DateTime result = this.fdate;
                // *** Start programmer edit section *** (Request.date Get end)

                // *** End programmer edit section *** (Request.date Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Request.date Set start)

                // *** End programmer edit section *** (Request.date Set start)
                this.fdate = value;
                // *** Start programmer edit section *** (Request.date Set end)

                // *** End programmer edit section *** (Request.date Set end)
            }
        }
        
        /// <summary>
        /// isCompleted.
        /// </summary>
        // *** Start programmer edit section *** (Request.isCompleted CustomAttributes)

        // *** End programmer edit section *** (Request.isCompleted CustomAttributes)
        [NotNull()]
        public virtual bool isCompleted
        {
            get
            {
                // *** Start programmer edit section *** (Request.isCompleted Get start)

                // *** End programmer edit section *** (Request.isCompleted Get start)
                bool result = this.fisCompleted;
                // *** Start programmer edit section *** (Request.isCompleted Get end)

                // *** End programmer edit section *** (Request.isCompleted Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Request.isCompleted Set start)

                // *** End programmer edit section *** (Request.isCompleted Set start)
                this.fisCompleted = value;
                // *** Start programmer edit section *** (Request.isCompleted Set end)

                // *** End programmer edit section *** (Request.isCompleted Set end)
            }
        }
        
        /// <summary>
        /// realDuration.
        /// </summary>
        // *** Start programmer edit section *** (Request.realDuration CustomAttributes)

        // *** End programmer edit section *** (Request.realDuration CustomAttributes)
        public virtual System.DateTime realDuration
        {
            get
            {
                // *** Start programmer edit section *** (Request.realDuration Get start)

                // *** End programmer edit section *** (Request.realDuration Get start)
                System.DateTime result = this.frealDuration;
                // *** Start programmer edit section *** (Request.realDuration Get end)

                // *** End programmer edit section *** (Request.realDuration Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Request.realDuration Set start)

                // *** End programmer edit section *** (Request.realDuration Set start)
                this.frealDuration = value;
                // *** Start programmer edit section *** (Request.realDuration Set end)

                // *** End programmer edit section *** (Request.realDuration Set end)
            }
        }
        
        /// <summary>
        /// Request.
        /// </summary>
        // *** Start programmer edit section *** (Request.Team CustomAttributes)

        // *** End programmer edit section *** (Request.Team CustomAttributes)
        [PropertyStorage(new string[] {
                "Team"})]
        public virtual IIS.Gorvodokanal.Team Team
        {
            get
            {
                // *** Start programmer edit section *** (Request.Team Get start)

                // *** End programmer edit section *** (Request.Team Get start)
                IIS.Gorvodokanal.Team result = this.fTeam;
                // *** Start programmer edit section *** (Request.Team Get end)

                // *** End programmer edit section *** (Request.Team Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Request.Team Set start)

                // *** End programmer edit section *** (Request.Team Set start)
                this.fTeam = value;
                // *** Start programmer edit section *** (Request.Team Set end)

                // *** End programmer edit section *** (Request.Team Set end)
            }
        }
        
        /// <summary>
        /// Request.
        /// </summary>
        // *** Start programmer edit section *** (Request.Address CustomAttributes)

        // *** End programmer edit section *** (Request.Address CustomAttributes)
        [PropertyStorage(new string[] {
                "Address"})]
        [NotNull()]
        public virtual IIS.Gorvodokanal.Address Address
        {
            get
            {
                // *** Start programmer edit section *** (Request.Address Get start)

                // *** End programmer edit section *** (Request.Address Get start)
                IIS.Gorvodokanal.Address result = this.fAddress;
                // *** Start programmer edit section *** (Request.Address Get end)

                // *** End programmer edit section *** (Request.Address Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Request.Address Set start)

                // *** End programmer edit section *** (Request.Address Set start)
                this.fAddress = value;
                // *** Start programmer edit section *** (Request.Address Set end)

                // *** End programmer edit section *** (Request.Address Set end)
            }
        }
        
        /// <summary>
        /// Request.
        /// </summary>
        // *** Start programmer edit section *** (Request.Tasks CustomAttributes)

        // *** End programmer edit section *** (Request.Tasks CustomAttributes)
        public virtual IIS.Gorvodokanal.DetailArrayOfTask Tasks
        {
            get
            {
                // *** Start programmer edit section *** (Request.Tasks Get start)

                // *** End programmer edit section *** (Request.Tasks Get start)
                if ((this.fTasks == null))
                {
                    this.fTasks = new IIS.Gorvodokanal.DetailArrayOfTask(this);
                }
                IIS.Gorvodokanal.DetailArrayOfTask result = this.fTasks;
                // *** Start programmer edit section *** (Request.Tasks Get end)

                // *** End programmer edit section *** (Request.Tasks Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Request.Tasks Set start)

                // *** End programmer edit section *** (Request.Tasks Set start)
                this.fTasks = value;
                // *** Start programmer edit section *** (Request.Tasks Set end)

                // *** End programmer edit section *** (Request.Tasks Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "RequestE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View RequestE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("RequestE", typeof(IIS.Gorvodokanal.Request));
                }
            }
            
            /// <summary>
            /// "RequestL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View RequestL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("RequestL", typeof(IIS.Gorvodokanal.Request));
                }
            }
        }
    }
}
