//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Gorvodokanal
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Request.
    /// </summary>
    // *** Start programmer edit section *** (Request CustomAttributes)

    // *** End programmer edit section *** (Request CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("RequestE", new string[] {
            "Iindex as \'Номер заявки\'",
            "Address as \'Адрес\' on \'-Данные об адресе\'",
            "Address.Street as \'Улица\' on \'-Данные об адресе\'",
            "Address.House as \'Дом\' on \'-Данные об адресе\'",
            "Address.Build as \'Корпус\' on \'-Данные об адресе\'",
            "Address.Floor as \'Этаж\' on \'-Данные об адресе\'",
            "Address.Apartment as \'Квартира\' on \'-Данные об адресе\'",
            "IsAppointed as \'Отметка о назначении\' on \'-Данные о выполнении\'",
            "Team as \'Бригада\' on \'-Данные о выполнении\'",
            "Team.Index as \'Номер бригады\' on \'-Данные о выполнении\'",
            "Date as \'Дата выполнения работ\' on \'-Данные о выполнении\'",
            "IsCompleted as \'Отметка о выполнении\' on \'-Данные о выполнении\'",
            "RealDuration as \'Фактическая длительность работ\' on \'-Данные о выполнении\'"})]
    [AssociatedDetailViewAttribute("RequestE", "Tasks", "TaskE", true, "", "Задачи", true, new string[] {
            ""})]
    [View("RequestL", new string[] {
            "Iindex as \'Номер заявки\'",
            "IsAppointed as \'Отметка о назначении\'",
            "Date as \'Дата выполнения работ\'",
            "IsCompleted as \'Отметка о выполнении\'",
            "Team.Index as \'Выполняющая бригада\'",
            "RealDuration as \'Фактическая длительность работ\'",
            "Address.Street as \'Улица\' on \'-Данные об адресе\'",
            "Address.House as \'Дом\' on \'-Данные об адресе\'",
            "Address.Build as \'Корпус\' on \'-Данные об адресе\'",
            "Address.Floor as \'Этаж\' on \'-Данные об адресе\'",
            "Address.Apartment as \'Квартира\' on \'-Данные об адресе\'"})]
    [AssociatedDetailViewAttribute("RequestL", "Tasks", "TaskE", true, "-Задачи", "", true, new string[] {
            ""})]
    public class Request : ICSSoft.STORMNET.DataObject
    {
        
        private int fIindex;
        
        private IIS.Gorvodokanal.tAppointed fIsAppointed;
        
        private System.DateTime fDate;
        
        private bool fIsCompleted = false;
        
        private System.DateTime fRealDuration;
        
        private IIS.Gorvodokanal.Team fTeam;
        
        private IIS.Gorvodokanal.Address fAddress;
        
        private IIS.Gorvodokanal.DetailArrayOfTask fTasks;
        
        // *** Start programmer edit section *** (Request CustomMembers)

        // *** End programmer edit section *** (Request CustomMembers)

        
        /// <summary>
        /// Iindex.
        /// </summary>
        // *** Start programmer edit section *** (Request.Iindex CustomAttributes)

        // *** End programmer edit section *** (Request.Iindex CustomAttributes)
        [NotNull()]
        public virtual int Iindex
        {
            get
            {
                // *** Start programmer edit section *** (Request.Iindex Get start)

                // *** End programmer edit section *** (Request.Iindex Get start)
                int result = this.fIindex;
                // *** Start programmer edit section *** (Request.Iindex Get end)

                // *** End programmer edit section *** (Request.Iindex Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Request.Iindex Set start)

                // *** End programmer edit section *** (Request.Iindex Set start)
                this.fIindex = value;
                // *** Start programmer edit section *** (Request.Iindex Set end)

                // *** End programmer edit section *** (Request.Iindex Set end)
            }
        }
        
        /// <summary>
        /// IsAppointed.
        /// </summary>
        // *** Start programmer edit section *** (Request.IsAppointed CustomAttributes)

        // *** End programmer edit section *** (Request.IsAppointed CustomAttributes)
        [NotNull()]
        public virtual IIS.Gorvodokanal.tAppointed IsAppointed
        {
            get
            {
                // *** Start programmer edit section *** (Request.IsAppointed Get start)

                // *** End programmer edit section *** (Request.IsAppointed Get start)
                IIS.Gorvodokanal.tAppointed result = this.fIsAppointed;
                // *** Start programmer edit section *** (Request.IsAppointed Get end)

                // *** End programmer edit section *** (Request.IsAppointed Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Request.IsAppointed Set start)

                // *** End programmer edit section *** (Request.IsAppointed Set start)
                this.fIsAppointed = value;
                // *** Start programmer edit section *** (Request.IsAppointed Set end)

                // *** End programmer edit section *** (Request.IsAppointed Set end)
            }
        }
        
        /// <summary>
        /// Date.
        /// </summary>
        // *** Start programmer edit section *** (Request.Date CustomAttributes)

        // *** End programmer edit section *** (Request.Date CustomAttributes)
        public virtual System.DateTime Date
        {
            get
            {
                // *** Start programmer edit section *** (Request.Date Get start)

                // *** End programmer edit section *** (Request.Date Get start)
                System.DateTime result = this.fDate;
                // *** Start programmer edit section *** (Request.Date Get end)

                // *** End programmer edit section *** (Request.Date Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Request.Date Set start)

                // *** End programmer edit section *** (Request.Date Set start)
                this.fDate = value;
                // *** Start programmer edit section *** (Request.Date Set end)

                // *** End programmer edit section *** (Request.Date Set end)
            }
        }
        
        /// <summary>
        /// IsCompleted.
        /// </summary>
        // *** Start programmer edit section *** (Request.IsCompleted CustomAttributes)

        // *** End programmer edit section *** (Request.IsCompleted CustomAttributes)
        public virtual bool IsCompleted
        {
            get
            {
                // *** Start programmer edit section *** (Request.IsCompleted Get start)

                // *** End programmer edit section *** (Request.IsCompleted Get start)
                bool result = this.fIsCompleted;
                // *** Start programmer edit section *** (Request.IsCompleted Get end)

                // *** End programmer edit section *** (Request.IsCompleted Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Request.IsCompleted Set start)

                // *** End programmer edit section *** (Request.IsCompleted Set start)
                this.fIsCompleted = value;
                // *** Start programmer edit section *** (Request.IsCompleted Set end)

                // *** End programmer edit section *** (Request.IsCompleted Set end)
            }
        }
        
        /// <summary>
        /// RealDuration.
        /// </summary>
        // *** Start programmer edit section *** (Request.RealDuration CustomAttributes)

        // *** End programmer edit section *** (Request.RealDuration CustomAttributes)
        public virtual System.DateTime RealDuration
        {
            get
            {
                // *** Start programmer edit section *** (Request.RealDuration Get start)

                // *** End programmer edit section *** (Request.RealDuration Get start)
                System.DateTime result = this.fRealDuration;
                // *** Start programmer edit section *** (Request.RealDuration Get end)

                // *** End programmer edit section *** (Request.RealDuration Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Request.RealDuration Set start)

                // *** End programmer edit section *** (Request.RealDuration Set start)
                this.fRealDuration = value;
                // *** Start programmer edit section *** (Request.RealDuration Set end)

                // *** End programmer edit section *** (Request.RealDuration Set end)
            }
        }
        
        /// <summary>
        /// Request.
        /// </summary>
        // *** Start programmer edit section *** (Request.Team CustomAttributes)

        // *** End programmer edit section *** (Request.Team CustomAttributes)
        [PropertyStorage(new string[] {
                "Team"})]
        public virtual IIS.Gorvodokanal.Team Team
        {
            get
            {
                // *** Start programmer edit section *** (Request.Team Get start)

                // *** End programmer edit section *** (Request.Team Get start)
                IIS.Gorvodokanal.Team result = this.fTeam;
                // *** Start programmer edit section *** (Request.Team Get end)

                // *** End programmer edit section *** (Request.Team Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Request.Team Set start)

                // *** End programmer edit section *** (Request.Team Set start)
                this.fTeam = value;
                // *** Start programmer edit section *** (Request.Team Set end)

                // *** End programmer edit section *** (Request.Team Set end)
            }
        }
        
        /// <summary>
        /// Request.
        /// </summary>
        // *** Start programmer edit section *** (Request.Address CustomAttributes)

        // *** End programmer edit section *** (Request.Address CustomAttributes)
        [PropertyStorage(new string[] {
                "Address"})]
        [NotNull()]
        public virtual IIS.Gorvodokanal.Address Address
        {
            get
            {
                // *** Start programmer edit section *** (Request.Address Get start)

                // *** End programmer edit section *** (Request.Address Get start)
                IIS.Gorvodokanal.Address result = this.fAddress;
                // *** Start programmer edit section *** (Request.Address Get end)

                // *** End programmer edit section *** (Request.Address Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Request.Address Set start)

                // *** End programmer edit section *** (Request.Address Set start)
                this.fAddress = value;
                // *** Start programmer edit section *** (Request.Address Set end)

                // *** End programmer edit section *** (Request.Address Set end)
            }
        }
        
        /// <summary>
        /// Request.
        /// </summary>
        // *** Start programmer edit section *** (Request.Tasks CustomAttributes)

        // *** End programmer edit section *** (Request.Tasks CustomAttributes)
        public virtual IIS.Gorvodokanal.DetailArrayOfTask Tasks
        {
            get
            {
                // *** Start programmer edit section *** (Request.Tasks Get start)

                // *** End programmer edit section *** (Request.Tasks Get start)
                if ((this.fTasks == null))
                {
                    this.fTasks = new IIS.Gorvodokanal.DetailArrayOfTask(this);
                }
                IIS.Gorvodokanal.DetailArrayOfTask result = this.fTasks;
                // *** Start programmer edit section *** (Request.Tasks Get end)

                // *** End programmer edit section *** (Request.Tasks Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Request.Tasks Set start)

                // *** End programmer edit section *** (Request.Tasks Set start)
                this.fTasks = value;
                // *** Start programmer edit section *** (Request.Tasks Set end)

                // *** End programmer edit section *** (Request.Tasks Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "RequestE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View RequestE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("RequestE", typeof(IIS.Gorvodokanal.Request));
                }
            }
            
            /// <summary>
            /// "RequestL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View RequestL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("RequestL", typeof(IIS.Gorvodokanal.Request));
                }
            }
        }
    }
}
