//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Gorvodokanal
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// T appointed.
    /// </summary>
    // *** Start programmer edit section *** (tAppointed CustomAttributes)

    // *** End programmer edit section *** (tAppointed CustomAttributes)
    public enum tAppointed
    {
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (tAppointed.Appointed CustomAttributes)

        // *** End programmer edit section *** (tAppointed.Appointed CustomAttributes)
        [Caption("назначено")]
        Appointed,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (tAppointed.NotAppointed CustomAttributes)

        // *** End programmer edit section *** (tAppointed.NotAppointed CustomAttributes)
        [Caption("не назначено")]
        NotAppointed,
    }
}
