//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Gorvodokanal
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Task.
    /// </summary>
    // *** Start programmer edit section *** (Task CustomAttributes)

    // *** End programmer edit section *** (Task CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("TaskE", new string[] {
            "Content as \'Содержание\'",
            "PlaneDuration as \'Примерная длительность работ\'"})]
    [View("TaskL", new string[] {
            "Content as \'Содержание\'",
            "PlaneDuration as \'Примерная длительность работ\'"})]
    public class Task : ICSSoft.STORMNET.DataObject
    {
        
        private string fContent;
        
        private System.DateTime fPlaneDuration;
        
        // *** Start programmer edit section *** (Task CustomMembers)

        // *** End programmer edit section *** (Task CustomMembers)

        
        /// <summary>
        /// Content.
        /// </summary>
        // *** Start programmer edit section *** (Task.Content CustomAttributes)

        // *** End programmer edit section *** (Task.Content CustomAttributes)
        [StrLen(255)]
        [NotNull()]
        public virtual string Content
        {
            get
            {
                // *** Start programmer edit section *** (Task.Content Get start)

                // *** End programmer edit section *** (Task.Content Get start)
                string result = this.fContent;
                // *** Start programmer edit section *** (Task.Content Get end)

                // *** End programmer edit section *** (Task.Content Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Task.Content Set start)

                // *** End programmer edit section *** (Task.Content Set start)
                this.fContent = value;
                // *** Start programmer edit section *** (Task.Content Set end)

                // *** End programmer edit section *** (Task.Content Set end)
            }
        }
        
        /// <summary>
        /// PlaneDuration.
        /// </summary>
        // *** Start programmer edit section *** (Task.PlaneDuration CustomAttributes)

        // *** End programmer edit section *** (Task.PlaneDuration CustomAttributes)
        public virtual System.DateTime PlaneDuration
        {
            get
            {
                // *** Start programmer edit section *** (Task.PlaneDuration Get start)

                // *** End programmer edit section *** (Task.PlaneDuration Get start)
                System.DateTime result = this.fPlaneDuration;
                // *** Start programmer edit section *** (Task.PlaneDuration Get end)

                // *** End programmer edit section *** (Task.PlaneDuration Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Task.PlaneDuration Set start)

                // *** End programmer edit section *** (Task.PlaneDuration Set start)
                this.fPlaneDuration = value;
                // *** Start programmer edit section *** (Task.PlaneDuration Set end)

                // *** End programmer edit section *** (Task.PlaneDuration Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "TaskE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View TaskE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("TaskE", typeof(IIS.Gorvodokanal.Task));
                }
            }
            
            /// <summary>
            /// "TaskL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View TaskL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("TaskL", typeof(IIS.Gorvodokanal.Task));
                }
            }
        }
    }
}
