//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Gorvodokanal
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// TaskList.
    /// </summary>
    // *** Start programmer edit section *** (TaskList CustomAttributes)

    // *** End programmer edit section *** (TaskList CustomAttributes)
    [AutoAltered()]
    [Caption("Список задач")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("TaskListE", new string[] {
            "Task as \'Задача\'",
            "Task.Index",
            "Task.Content",
            "Task.PlaneDuration",
            "Task.Importance"}, Hidden=new string[] {
            "Task.Importance"})]
    [MasterViewDefineAttribute("TaskListE", "Task", ICSSoft.STORMNET.LookupTypeEnum.Combo, "", "Content")]
    public class TaskList : ICSSoft.STORMNET.DataObject
    {
        
        private IIS.Gorvodokanal.Task fTask;
        
        private IIS.Gorvodokanal.Request fRequest;
        
        // *** Start programmer edit section *** (TaskList CustomMembers)

        // *** End programmer edit section *** (TaskList CustomMembers)

        
        /// <summary>
        /// TaskList.
        /// </summary>
        // *** Start programmer edit section *** (TaskList.Task CustomAttributes)

        // *** End programmer edit section *** (TaskList.Task CustomAttributes)
        [PropertyStorage(new string[] {
                "Task"})]
        [NotNull()]
        public virtual IIS.Gorvodokanal.Task Task
        {
            get
            {
                // *** Start programmer edit section *** (TaskList.Task Get start)

                // *** End programmer edit section *** (TaskList.Task Get start)
                IIS.Gorvodokanal.Task result = this.fTask;
                // *** Start programmer edit section *** (TaskList.Task Get end)

                // *** End programmer edit section *** (TaskList.Task Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (TaskList.Task Set start)

                // *** End programmer edit section *** (TaskList.Task Set start)
                this.fTask = value;
                // *** Start programmer edit section *** (TaskList.Task Set end)

                // *** End programmer edit section *** (TaskList.Task Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Gorvodokanal.Request.
        /// </summary>
        // *** Start programmer edit section *** (TaskList.Request CustomAttributes)

        // *** End programmer edit section *** (TaskList.Request CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Request"})]
        public virtual IIS.Gorvodokanal.Request Request
        {
            get
            {
                // *** Start programmer edit section *** (TaskList.Request Get start)

                // *** End programmer edit section *** (TaskList.Request Get start)
                IIS.Gorvodokanal.Request result = this.fRequest;
                // *** Start programmer edit section *** (TaskList.Request Get end)

                // *** End programmer edit section *** (TaskList.Request Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (TaskList.Request Set start)

                // *** End programmer edit section *** (TaskList.Request Set start)
                this.fRequest = value;
                // *** Start programmer edit section *** (TaskList.Request Set end)

                // *** End programmer edit section *** (TaskList.Request Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "TaskListE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View TaskListE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("TaskListE", typeof(IIS.Gorvodokanal.TaskList));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of TaskList.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfTaskList CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfTaskList CustomAttributes)
    public class DetailArrayOfTaskList : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Gorvodokanal.DetailArrayOfTaskList members)

        // *** End programmer edit section *** (IIS.Gorvodokanal.DetailArrayOfTaskList members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type TaskList by index.
        /// </summary>
        /// <summary>
        /// Adds object with type TaskList.
        /// </summary>
        public DetailArrayOfTaskList(IIS.Gorvodokanal.Request fRequest) : 
                base(typeof(TaskList), ((ICSSoft.STORMNET.DataObject)(fRequest)))
        {
        }
        
        public IIS.Gorvodokanal.TaskList this[int index]
        {
            get
            {
                return ((IIS.Gorvodokanal.TaskList)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Gorvodokanal.TaskList dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
