//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Gorvodokanal
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Task.
    /// </summary>
    // *** Start programmer edit section *** (Task CustomAttributes)

    // *** End programmer edit section *** (Task CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("TaskE", new string[] {
            "Index",
            "Category as \'Категория\'",
            "Content as \'Детали\'",
            "PlaneDuration as \'Примерная длительность работ\'",
            "Importance as \'Срочность\'"}, Hidden=new string[] {
            "Index"})]
    [View("TaskL", new string[] {
            "Category.Name as \'Категория\'",
            "Content as \'Детали\'",
            "PlaneDuration as \'Примерная длительность работ\'",
            "Importance as \'Срочнось\'"})]
    public class Task : ICSSoft.STORMNET.DataObject
    {
        
        private int fIndex = 1;
        
        private string fContent;
        
        private System.DateTime fPlaneDuration;
        
        private IIS.Gorvodokanal.tImportance fImportance;
        
        private IIS.Gorvodokanal.Category fCategory;
        
        // *** Start programmer edit section *** (Task CustomMembers)

        // *** End programmer edit section *** (Task CustomMembers)

        
        /// <summary>
        /// Index.
        /// </summary>
        // *** Start programmer edit section *** (Task.Index CustomAttributes)

        // *** End programmer edit section *** (Task.Index CustomAttributes)
        [DisableInsertProperty(true)]
        [NotNull()]
        public virtual int Index
        {
            get
            {
                // *** Start programmer edit section *** (Task.Index Get start)

                // *** End programmer edit section *** (Task.Index Get start)
                int result = this.fIndex;
                // *** Start programmer edit section *** (Task.Index Get end)

                // *** End programmer edit section *** (Task.Index Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Task.Index Set start)

                // *** End programmer edit section *** (Task.Index Set start)
                this.fIndex = value;
                // *** Start programmer edit section *** (Task.Index Set end)

                // *** End programmer edit section *** (Task.Index Set end)
            }
        }
        
        /// <summary>
        /// Content.
        /// </summary>
        // *** Start programmer edit section *** (Task.Content CustomAttributes)

        // *** End programmer edit section *** (Task.Content CustomAttributes)
        [StrLen(255)]
        [NotNull()]
        public virtual string Content
        {
            get
            {
                // *** Start programmer edit section *** (Task.Content Get start)

                // *** End programmer edit section *** (Task.Content Get start)
                string result = this.fContent;
                // *** Start programmer edit section *** (Task.Content Get end)

                // *** End programmer edit section *** (Task.Content Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Task.Content Set start)

                // *** End programmer edit section *** (Task.Content Set start)
                this.fContent = value;
                // *** Start programmer edit section *** (Task.Content Set end)

                // *** End programmer edit section *** (Task.Content Set end)
            }
        }
        
        /// <summary>
        /// PlaneDuration.
        /// </summary>
        // *** Start programmer edit section *** (Task.PlaneDuration CustomAttributes)

        // *** End programmer edit section *** (Task.PlaneDuration CustomAttributes)
        public virtual System.DateTime PlaneDuration
        {
            get
            {
                // *** Start programmer edit section *** (Task.PlaneDuration Get start)

                // *** End programmer edit section *** (Task.PlaneDuration Get start)
                System.DateTime result = this.fPlaneDuration;
                // *** Start programmer edit section *** (Task.PlaneDuration Get end)

                // *** End programmer edit section *** (Task.PlaneDuration Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Task.PlaneDuration Set start)

                // *** End programmer edit section *** (Task.PlaneDuration Set start)
                this.fPlaneDuration = value;
                // *** Start programmer edit section *** (Task.PlaneDuration Set end)

                // *** End programmer edit section *** (Task.PlaneDuration Set end)
            }
        }
        
        /// <summary>
        /// Importance.
        /// </summary>
        // *** Start programmer edit section *** (Task.Importance CustomAttributes)

        // *** End programmer edit section *** (Task.Importance CustomAttributes)
        public virtual IIS.Gorvodokanal.tImportance Importance
        {
            get
            {
                // *** Start programmer edit section *** (Task.Importance Get start)

                // *** End programmer edit section *** (Task.Importance Get start)
                IIS.Gorvodokanal.tImportance result = this.fImportance;
                // *** Start programmer edit section *** (Task.Importance Get end)

                // *** End programmer edit section *** (Task.Importance Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Task.Importance Set start)

                // *** End programmer edit section *** (Task.Importance Set start)
                this.fImportance = value;
                // *** Start programmer edit section *** (Task.Importance Set end)

                // *** End programmer edit section *** (Task.Importance Set end)
            }
        }
        
        /// <summary>
        /// Task.
        /// </summary>
        // *** Start programmer edit section *** (Task.Category CustomAttributes)

        // *** End programmer edit section *** (Task.Category CustomAttributes)
        [PropertyStorage(new string[] {
                "Category"})]
        [NotNull()]
        public virtual IIS.Gorvodokanal.Category Category
        {
            get
            {
                // *** Start programmer edit section *** (Task.Category Get start)

                // *** End programmer edit section *** (Task.Category Get start)
                IIS.Gorvodokanal.Category result = this.fCategory;
                // *** Start programmer edit section *** (Task.Category Get end)

                // *** End programmer edit section *** (Task.Category Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Task.Category Set start)

                // *** End programmer edit section *** (Task.Category Set start)
                this.fCategory = value;
                // *** Start programmer edit section *** (Task.Category Set end)

                // *** End programmer edit section *** (Task.Category Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "TaskE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View TaskE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("TaskE", typeof(IIS.Gorvodokanal.Task));
                }
            }
            
            /// <summary>
            /// "TaskL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View TaskL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("TaskL", typeof(IIS.Gorvodokanal.Task));
                }
            }
        }
    }
}
