//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Gorvodokanal
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// T districts.
    /// </summary>
    // *** Start programmer edit section *** (tDistricts CustomAttributes)

    // *** End programmer edit section *** (tDistricts CustomAttributes)
    public enum tDistricts
    {
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (tDistricts.Motovilikhinsky CustomAttributes)

        // *** End programmer edit section *** (tDistricts.Motovilikhinsky CustomAttributes)
        [Caption("Мотовилихинский")]
        Motovilikhinsky,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (tDistricts.Ordzhonikidzevsky CustomAttributes)

        // *** End programmer edit section *** (tDistricts.Ordzhonikidzevsky CustomAttributes)
        [Caption("Орджоникидзовский")]
        Ordzhonikidzevsky,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (tDistricts.Leninsky CustomAttributes)

        // *** End programmer edit section *** (tDistricts.Leninsky CustomAttributes)
        [Caption("Ленинский")]
        Leninsky,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (tDistricts.Kirovsky CustomAttributes)

        // *** End programmer edit section *** (tDistricts.Kirovsky CustomAttributes)
        [Caption("Кировский")]
        Kirovsky,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (tDistricts.Dzerzhinsky CustomAttributes)

        // *** End programmer edit section *** (tDistricts.Dzerzhinsky CustomAttributes)
        [Caption("Дзержинский")]
        Dzerzhinsky,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (tDistricts.Industrialny CustomAttributes)

        // *** End programmer edit section *** (tDistricts.Industrialny CustomAttributes)
        [Caption("Индустриальный")]
        Industrialny,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (tDistricts.Sverdlovsky CustomAttributes)

        // *** End programmer edit section *** (tDistricts.Sverdlovsky CustomAttributes)
        [Caption("Свердловский")]
        Sverdlovsky,
    }
}
