//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Gorvodokanal
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Team.
    /// </summary>
    // *** Start programmer edit section *** (Team CustomAttributes)

    // *** End programmer edit section *** (Team CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("TeamE", new string[] {
            "index as \'Индекс бригады\'",
            "shiftStart as \'Начало смены\'",
            "shiftEnd as \'Конец смены\'"})]
    [View("TeamL", new string[] {
            "index as \'Индекс бригады\'",
            "shiftStart as \'Начало смены\'",
            "shiftEnd as \'Конец смены\'"})]
    public class Team : ICSSoft.STORMNET.DataObject
    {
        
        private int findex;
        
        private System.DateTime fshiftStart;
        
        private System.DateTime fshiftEnd;
        
        // *** Start programmer edit section *** (Team CustomMembers)

        // *** End programmer edit section *** (Team CustomMembers)

        
        /// <summary>
        /// index.
        /// </summary>
        // *** Start programmer edit section *** (Team.index CustomAttributes)

        // *** End programmer edit section *** (Team.index CustomAttributes)
        [NotNull()]
        public virtual int index
        {
            get
            {
                // *** Start programmer edit section *** (Team.index Get start)

                // *** End programmer edit section *** (Team.index Get start)
                int result = this.findex;
                // *** Start programmer edit section *** (Team.index Get end)

                // *** End programmer edit section *** (Team.index Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Team.index Set start)

                // *** End programmer edit section *** (Team.index Set start)
                this.findex = value;
                // *** Start programmer edit section *** (Team.index Set end)

                // *** End programmer edit section *** (Team.index Set end)
            }
        }
        
        /// <summary>
        /// shiftStart.
        /// </summary>
        // *** Start programmer edit section *** (Team.shiftStart CustomAttributes)

        // *** End programmer edit section *** (Team.shiftStart CustomAttributes)
        [NotNull()]
        public virtual System.DateTime shiftStart
        {
            get
            {
                // *** Start programmer edit section *** (Team.shiftStart Get start)

                // *** End programmer edit section *** (Team.shiftStart Get start)
                System.DateTime result = this.fshiftStart;
                // *** Start programmer edit section *** (Team.shiftStart Get end)

                // *** End programmer edit section *** (Team.shiftStart Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Team.shiftStart Set start)

                // *** End programmer edit section *** (Team.shiftStart Set start)
                this.fshiftStart = value;
                // *** Start programmer edit section *** (Team.shiftStart Set end)

                // *** End programmer edit section *** (Team.shiftStart Set end)
            }
        }
        
        /// <summary>
        /// shiftEnd.
        /// </summary>
        // *** Start programmer edit section *** (Team.shiftEnd CustomAttributes)

        // *** End programmer edit section *** (Team.shiftEnd CustomAttributes)
        [NotNull()]
        public virtual System.DateTime shiftEnd
        {
            get
            {
                // *** Start programmer edit section *** (Team.shiftEnd Get start)

                // *** End programmer edit section *** (Team.shiftEnd Get start)
                System.DateTime result = this.fshiftEnd;
                // *** Start programmer edit section *** (Team.shiftEnd Get end)

                // *** End programmer edit section *** (Team.shiftEnd Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Team.shiftEnd Set start)

                // *** End programmer edit section *** (Team.shiftEnd Set start)
                this.fshiftEnd = value;
                // *** Start programmer edit section *** (Team.shiftEnd Set end)

                // *** End programmer edit section *** (Team.shiftEnd Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "TeamE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View TeamE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("TeamE", typeof(IIS.Gorvodokanal.Team));
                }
            }
            
            /// <summary>
            /// "TeamL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View TeamL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("TeamL", typeof(IIS.Gorvodokanal.Team));
                }
            }
        }
    }
}
