//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Gorvodokanal
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Team.
    /// </summary>
    // *** Start programmer edit section *** (Team CustomAttributes)

    // *** End programmer edit section *** (Team CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("TeamE", new string[] {
            "Index as \'Номер бригады\'",
            "ShiftStart as \'Начало смены\'",
            "ShiftEnd as \'Конец смены\'"})]
    [View("TeamL", new string[] {
            "Index as \'Номер бригады\'",
            "ShiftStart as \'Начало смены\'",
            "ShiftEnd as \'Конец смены\'"})]
    public class Team : ICSSoft.STORMNET.DataObject
    {
        
        private int fIndex;
        
        private System.DateTime fShiftStart;
        
        private System.DateTime fShiftEnd;
        
        // *** Start programmer edit section *** (Team CustomMembers)

        // *** End programmer edit section *** (Team CustomMembers)

        
        /// <summary>
        /// Index.
        /// </summary>
        // *** Start programmer edit section *** (Team.Index CustomAttributes)

        // *** End programmer edit section *** (Team.Index CustomAttributes)
        [NotNull()]
        public virtual int Index
        {
            get
            {
                // *** Start programmer edit section *** (Team.Index Get start)

                // *** End programmer edit section *** (Team.Index Get start)
                int result = this.fIndex;
                // *** Start programmer edit section *** (Team.Index Get end)

                // *** End programmer edit section *** (Team.Index Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Team.Index Set start)

                // *** End programmer edit section *** (Team.Index Set start)
                this.fIndex = value;
                // *** Start programmer edit section *** (Team.Index Set end)

                // *** End programmer edit section *** (Team.Index Set end)
            }
        }
        
        /// <summary>
        /// ShiftStart.
        /// </summary>
        // *** Start programmer edit section *** (Team.ShiftStart CustomAttributes)

        // *** End programmer edit section *** (Team.ShiftStart CustomAttributes)
        public virtual System.DateTime ShiftStart
        {
            get
            {
                // *** Start programmer edit section *** (Team.ShiftStart Get start)

                // *** End programmer edit section *** (Team.ShiftStart Get start)
                System.DateTime result = this.fShiftStart;
                // *** Start programmer edit section *** (Team.ShiftStart Get end)

                // *** End programmer edit section *** (Team.ShiftStart Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Team.ShiftStart Set start)

                // *** End programmer edit section *** (Team.ShiftStart Set start)
                this.fShiftStart = value;
                // *** Start programmer edit section *** (Team.ShiftStart Set end)

                // *** End programmer edit section *** (Team.ShiftStart Set end)
            }
        }
        
        /// <summary>
        /// ShiftEnd.
        /// </summary>
        // *** Start programmer edit section *** (Team.ShiftEnd CustomAttributes)

        // *** End programmer edit section *** (Team.ShiftEnd CustomAttributes)
        public virtual System.DateTime ShiftEnd
        {
            get
            {
                // *** Start programmer edit section *** (Team.ShiftEnd Get start)

                // *** End programmer edit section *** (Team.ShiftEnd Get start)
                System.DateTime result = this.fShiftEnd;
                // *** Start programmer edit section *** (Team.ShiftEnd Get end)

                // *** End programmer edit section *** (Team.ShiftEnd Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Team.ShiftEnd Set start)

                // *** End programmer edit section *** (Team.ShiftEnd Set start)
                this.fShiftEnd = value;
                // *** Start programmer edit section *** (Team.ShiftEnd Set end)

                // *** End programmer edit section *** (Team.ShiftEnd Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "TeamE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View TeamE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("TeamE", typeof(IIS.Gorvodokanal.Team));
                }
            }
            
            /// <summary>
            /// "TeamL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View TeamL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("TeamL", typeof(IIS.Gorvodokanal.Team));
                }
            }
        }
    }
}
