//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Gorvodokanal
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// tImportance.
    /// </summary>
    // *** Start programmer edit section *** (tImportance CustomAttributes)

    // *** End programmer edit section *** (tImportance CustomAttributes)
    public enum tImportance
    {
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (tImportance.NotImportant CustomAttributes)

        // *** End programmer edit section *** (tImportance.NotImportant CustomAttributes)
        [Caption("не срочно (0)")]
        NotImportant,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (tImportance.LowImportance CustomAttributes)

        // *** End programmer edit section *** (tImportance.LowImportance CustomAttributes)
        [Caption("малая срочность (1)")]
        LowImportance,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (tImportance.MiddleImportance CustomAttributes)

        // *** End programmer edit section *** (tImportance.MiddleImportance CustomAttributes)
        [Caption("средняя срочность (2)")]
        MiddleImportance,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (tImportance.HighImportance CustomAttributes)

        // *** End programmer edit section *** (tImportance.HighImportance CustomAttributes)
        [Caption("высокая срочность (3)")]
        HighImportance,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (tImportance.ExtrimlyImportant CustomAttributes)

        // *** End programmer edit section *** (tImportance.ExtrimlyImportant CustomAttributes)
        [Caption("как можно скорее (4)")]
        ExtrimlyImportant,
    }
}
