



CREATE TABLE Task (

 primaryKey UUID NOT NULL,

 code INT NOT NULL,

 content VARCHAR(255) NOT NULL,

 planeDuration TIMESTAMP(3) NOT NULL,

 Request UUID NOT NULL,

 PRIMARY KEY (primaryKey));


CREATE TABLE Request (

 primaryKey UUID NOT NULL,

 index INT NOT NULL,

 isAppointed VARCHAR(13) NOT NULL,

 date TIMESTAMP(3) NULL,

 isCompleted BOOLEAN NOT NULL,

 realDuration TIMESTAMP(3) NULL,

 Team UUID NULL,

 Address UUID NOT NULL,

 PRIMARY KEY (primaryKey));


CREATE TABLE Address (

 primaryKey UUID NOT NULL,

 index INT NOT NULL,

 street VARCHAR(255) NOT NULL,

 house INT NOT NULL,

 build VARCHAR(255) NULL,

 floor INT NULL,

 flat INT NULL,

 PRIMARY KEY (primaryKey));


CREATE TABLE Team (

 primaryKey UUID NOT NULL,

 index INT NOT NULL,

 shiftStart TIMESTAMP(3) NOT NULL,

 shiftEnd TIMESTAMP(3) NOT NULL,

 PRIMARY KEY (primaryKey));


CREATE TABLE STORMNETLOCKDATA (

 LockKey VARCHAR(300) NOT NULL,

 UserName VARCHAR(300) NOT NULL,

 LockDate TIMESTAMP(3) NULL,

 PRIMARY KEY (LockKey));


CREATE TABLE STORMSETTINGS (

 primaryKey UUID NOT NULL,

 Module VARCHAR(1000) NULL,

 Name VARCHAR(255) NULL,

 Value TEXT NULL,

 "User" VARCHAR(255) NULL,

 PRIMARY KEY (primaryKey));


CREATE TABLE STORMAdvLimit (

 primaryKey UUID NOT NULL,

 "User" VARCHAR(255) NULL,

 Published BOOLEAN NULL,

 Module VARCHAR(255) NULL,

 Name VARCHAR(255) NULL,

 Value TEXT NULL,

 HotKeyData INT NULL,

 PRIMARY KEY (primaryKey));


CREATE TABLE STORMFILTERSETTING (

 primaryKey UUID NOT NULL,

 Name VARCHAR(255) NOT NULL,

 DataObjectView VARCHAR(255) NOT NULL,

 PRIMARY KEY (primaryKey));


CREATE TABLE STORMWEBSEARCH (

 primaryKey UUID NOT NULL,

 Name VARCHAR(255) NOT NULL,

 "Order" INT NOT NULL,

 PresentView VARCHAR(255) NOT NULL,

 DetailedView VARCHAR(255) NOT NULL,

 FilterSetting_m0 UUID NOT NULL,

 PRIMARY KEY (primaryKey));


CREATE TABLE STORMFILTERDETAIL (

 primaryKey UUID NOT NULL,

 Caption VARCHAR(255) NOT NULL,

 DataObjectView VARCHAR(255) NOT NULL,

 ConnectMasterProp VARCHAR(255) NOT NULL,

 OwnerConnectProp VARCHAR(255) NULL,

 FilterSetting_m0 UUID NOT NULL,

 PRIMARY KEY (primaryKey));


CREATE TABLE STORMFILTERLOOKUP (

 primaryKey UUID NOT NULL,

 DataObjectType VARCHAR(255) NOT NULL,

 Container VARCHAR(255) NULL,

 ContainerTag VARCHAR(255) NULL,

 FieldsToView VARCHAR(255) NULL,

 FilterSetting_m0 UUID NOT NULL,

 PRIMARY KEY (primaryKey));


CREATE TABLE UserSetting (

 primaryKey UUID NOT NULL,

 AppName VARCHAR(256) NULL,

 UserName VARCHAR(512) NULL,

 UserGuid UUID NULL,

 ModuleName VARCHAR(1024) NULL,

 ModuleGuid UUID NULL,

 SettName VARCHAR(256) NULL,

 SettGuid UUID NULL,

 SettLastAccessTime TIMESTAMP(3) NULL,

 StrVal VARCHAR(256) NULL,

 TxtVal TEXT NULL,

 IntVal INT NULL,

 BoolVal BOOLEAN NULL,

 GuidVal UUID NULL,

 DecimalVal DECIMAL(20,10) NULL,

 DateTimeVal TIMESTAMP(3) NULL,

 PRIMARY KEY (primaryKey));


CREATE TABLE ApplicationLog (

 primaryKey UUID NOT NULL,

 Category VARCHAR(64) NULL,

 EventId INT NULL,

 Priority INT NULL,

 Severity VARCHAR(32) NULL,

 Title VARCHAR(256) NULL,

 Timestamp TIMESTAMP(3) NULL,

 MachineName VARCHAR(32) NULL,

 AppDomainName VARCHAR(512) NULL,

 ProcessId VARCHAR(256) NULL,

 ProcessName VARCHAR(512) NULL,

 ThreadName VARCHAR(512) NULL,

 Win32ThreadId VARCHAR(128) NULL,

 Message VARCHAR(2500) NULL,

 FormattedMessage TEXT NULL,

 PRIMARY KEY (primaryKey));




 ALTER TABLE Task ADD CONSTRAINT FKad814c51c01c42e684bc48c06ec0f44c FOREIGN KEY (Request) REFERENCES Request; 
CREATE INDEX Index602fb54d4e3142c0b2fb2de4e74a2ce5 on Task (Request); 

 ALTER TABLE Request ADD CONSTRAINT FKcc2ad1befced46498da288b640ede2b3 FOREIGN KEY (Team) REFERENCES Team; 
CREATE INDEX Indexadc21acf6f784b77a734a03a4070676f on Request (Team); 

 ALTER TABLE Request ADD CONSTRAINT FK3d58f38bb5504357aa41a14ff86abdd9 FOREIGN KEY (Address) REFERENCES Address; 
CREATE INDEX Indexc367128d3fd841bc87153326c3f0ccd9 on Request (Address); 

 ALTER TABLE STORMWEBSEARCH ADD CONSTRAINT FKf54f714e73eb4314b28a7d1461c12a6b FOREIGN KEY (FilterSetting_m0) REFERENCES STORMFILTERSETTING; 

 ALTER TABLE STORMFILTERDETAIL ADD CONSTRAINT FK8bbb34b169e64af890304e9e14ebe5ef FOREIGN KEY (FilterSetting_m0) REFERENCES STORMFILTERSETTING; 

 ALTER TABLE STORMFILTERLOOKUP ADD CONSTRAINT FKe83a59a94fba40928a31589e9c728d71 FOREIGN KEY (FilterSetting_m0) REFERENCES STORMFILTERSETTING; 

